import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../lib/AuthContext";

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      await login(email, password);
      navigate("/");
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="login-shell">
      {/* Left: brand panel */}
      <div className="login-brand-panel">
        <div className="login-brand-logo">
          <div className="login-brand-logo-icon">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>
            </svg>
          </div>
          <span className="login-brand-name">Optiview</span>
        </div>

        <h1 className="login-headline">
          AI-powered <span>e-commerce</span> optimization
        </h1>
        <p className="login-desc">
          Connect your Shopify store and let AI analyze your data to surface the highest-impact recommendations — in minutes.
        </p>

        <div className="login-features">
          {[
            "Pricing opportunities identified automatically",
            "Declining products flagged before it's too late",
            "Cross-sell campaigns generated by AI",
            "Inventory alerts based on real sales velocity",
          ].map((f) => (
            <div key={f} className="login-feature">
              <span className="login-feature-dot" />
              {f}
            </div>
          ))}
        </div>
      </div>

      {/* Right: form */}
      <div className="login-form-panel">
        <div className="login-form-box fade-up">
          <h2 className="login-form-title">Welcome back</h2>
          <p className="login-form-sub">Sign in to see what your store should optimize next.</p>

          <form className="login-form-fields" onSubmit={handleSubmit}>
            <div>
              <label className="form-label" htmlFor="login-email">Email</label>
              <input
                id="login-email"
                className="input"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="you@store.com"
                autoFocus
              />
            </div>
            <div>
              <label className="form-label" htmlFor="login-password">Password</label>
              <input
                id="login-password"
                className="input"
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••"
              />
            </div>

            {error && <div className="alert-error">{error}</div>}

            <button
              id="login-submit"
              type="submit"
              disabled={loading}
              className="btn btn-primary"
              style={{ width: "100%", justifyContent: "center", marginTop: 4, padding: "12px 0", fontSize: 14 }}
            >
              {loading ? (
                <>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" style={{ animation: "spin 0.8s linear infinite" }}>
                    <path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" opacity="0.3"/>
                    <path d="M21 12a9 9 0 00-9-9"/>
                  </svg>
                  Signing in…
                </>
              ) : "Sign in"}
            </button>

            {/* Quick Demo Fill */}
            <div style={{ marginTop: 14, paddingTop: 14, borderTop: "1px solid var(--line)", textAlign: "center" }}>
              <button
                type="button"
                className="btn btn-ghost"
                style={{ width: "100%", justifyContent: "center", fontSize: 12, color: "var(--brand)" }}
                onClick={() => {
                  setEmail("demo@elvirainfotech.com");
                  setPassword("demo1234");
                }}
              >
                ⚡ Use Demo Credentials (demo@elvirainfotech.com)
              </button>
            </div>
          </form>
        </div>
      </div>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
